DATA:
  IMAGE_DIR: '/home/hasnain/Downloads/DIV2K'
  HIGH_RES_CROP_SIZE: 128
GENERATOR:
  NUM_FILTERS: 32
  NUM_BLOCKS: 16
  LEARNING_RATE: 1e-4
DISCRIMINATOR:
  NUM_FILTERS: 32
  NUM_BLOCKS: 3
  LEARNING_RATE: 1e-4
FEATURE_EXTRACTOR:
  FEATURE_LAYER: 34
LOSS:
  ADVERSARIAL_WEIGHT: 1e-2
  FEATURE_WEIGHT: 1e-2
  PIXEL_WEIGHT: 1
TRAINING:
  EPOCHS: 2000
  BATCH_SIZE: 12
  NUM_WORKERS: 4
  GPUS: 1
  RESUME_FROM_CKPT: 'weights/epoch=999-step=66999-v3.ckpt'