DATA:
  IMAGE_DIR: '/home/hasnain/Datasets/DIV2K_train_HR'
  HIGH_RES_CROP_SIZE: 256
GENERATOR:
  NUM_FILTERS: 32
  NUM_BLOCKS: 8
  LEARNING_RATE: 1e-4
DISCRIMINATOR:
  NUM_FILTERS: 32
  NUM_BLOCKS: 3
  LEARNING_RATE: 1e-4
FEATURE_EXTRACTOR:
  FEATURE_LAYER: 34
LOSS:
  ADVERSARIAL_WEIGHT: 1e-2
  FEATURE_WEIGHT: 1e-2
  PIXEL_WEIGHT: 1
TRAINING:
  EPOCHS: 4000
  BATCH_SIZE: 24
  NUM_WORKERS: 4
  GPUS: 1
  RESUME_FROM_CKPT: ~
